version: "3.5"

services:
  app:
    build:
      context: .
      target: DEVELOPMENT
    env_file:
      - .env
    volumes:
      - $PWD:/usr/src/app/
      - gems:/usr/local/bundle/

volumes:
  gems: {}
